import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI

// Background handler
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp();
  print('Background message received: ${message.notification?.title}');
  print('Custom data: ${message.data}');
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'FCM Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: MessagingScreen(),
    );
  }
}

class MessagingScreen extends StatefulWidget {
  @override
  _MessagingScreenState createState() => _MessagingScreenState();
}

class _MessagingScreenState extends State<MessagingScreen> {
  String? token = "";
  String notificationText = "No notification yet";
  Color notificationColor = Colors.grey;
  IconData notificationIcon = Icons.notifications;

  @override
  void initState() {
    super.initState();
    _getToken();
    _setupFCMListeners();
  }

  void _getToken() async {
    token = await FirebaseMessaging.instance.getToken();
    print("FCM Token: $token"); // Copy this token to Firebase Console for testing
    setState(() {});
  }

  void _setupFCMListeners() {
    // Foreground message
    FirebaseMessaging.onMessage.listen((RemoteMessage message) {
      print("Foreground message received: ${message.notification?.body}");
      _showNotification(message);
    });

    // When user taps notification
    FirebaseMessaging.onMessageOpenedApp.listen((RemoteMessage message) {
      print("Notification clicked!");
      _showNotification(message);
    });
  }

  void _showNotification(RemoteMessage message) {
    String? type = message.data['type'];
    setState(() {
      notificationText = message.notification?.body ?? "No message";

      // Customize based on type
      switch (type) {
        case 'regular':
          notificationColor = Colors.grey;
          notificationIcon = Icons.message;
          break;
        case 'important':
          notificationColor = Colors.red;
          notificationIcon = Icons.warning;
          break;
        case 'wisdom':
          notificationColor = Colors.purple;
          notificationIcon = Icons.lightbulb;
          break;
        default:
          notificationColor = Colors.blue;
          notificationIcon = Icons.notifications;
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("Firebase Messaging Demo")),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          children: [
            Text(
              "Your FCM Token (copy this for testing):",
              style: TextStyle(fontWeight: FontWeight.bold),
            ),
            SelectableText(token ?? "Fetching..."),
            SizedBox(height: 20),
            Divider(),
            SizedBox(height: 20),
            Text(
              "Latest Notification:",
              style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18),
            ),
            SizedBox(height: 10),
            Card(
              color: notificationColor.withOpacity(0.3),
              child: ListTile(
                leading: Icon(notificationIcon, color: notificationColor),
                title: Text(notificationText),
              ),
            )
          ],
        ),
      ),
    );
  }
}
